### ISSUE TITLE
UI crash when oping plugin install page

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#390]
```
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/edge/system/networking/factory.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/edge/system/networking/views/edit.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/rubix-flow/util/autoLayout.ts'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/rubix-flow/util/hasPositionMetaData.ts'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/rubix-flow/util/isValidConnection.ts'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/rubix-flow/components/AutoSizeInput.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/rubix-flow/components/Modals/SetNameModal.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/common/rb-version.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/common/rb-tag.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/views/utils.ts'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/release/factory.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/views/install-rubix-app/install-rubix-app-modal.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/views/install-rubix-app/factory.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/host/flow/plugins/views/plugin-download-modal.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/views/install-rubix-app/installation.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/components/hosts/views/install-rubix-app/completion.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/themes/dark-theme.tsx'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/node_modules/antd/dist/antd.dark.css'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/assets/images/nube-frog-green.png'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/themes/dark-theme.css'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/assets/images/RC5.png'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/assets/images/Nube-logo.png'
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/src/assets/images/BACnet_logo.png'
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x7fdb94f8cd77
stack: frame={sp:0xc000365c10, fp:0xc000365c60} stack=[0xc00035db10,0xc000365f10)
0x000000c000365b10:  0x000000000000000b  0x000000c000365b48 
0x000000c000365b20:  0x000000c000365b70  0x000000c000365b98 
0x000000c000365b30:  0x0020300000000000  0x000000c000010578 
0x000000c000365b40:  0x0000000000000000  0x000000c000604000 
0x000000c000365b50:  0x0000000000000000  0x0000000000008000 
0x000000c000365b60:  0x000000c000365bd8  0x000000000045533b <runtime.sigtrampgo+0x000000000000013b> 
0x000000c000365b70:  0x000000c00000000b  0x000000c000600000 
0x000000c000365b80:  0x0000000000000006  0x0000000000000005 
0x000000c000365b90:  0x0000000000000001  0x0000000000000000 
0x000000c000365ba0:  0x0000000000000000  0x0000000000000000 
0x000000c000365bb0:  0x0000000000000000  0x0000000000000000 
0x000000c000365bc0:  0x000000c000679040  0x000000c000365eb0 
0x000000c000365bd0:  0x000000c000365d80  0x000000c000365c00 
0x000000c000365be0:  0x000000000047408e <runtime.sigtrampgo+0x000000000000002e>  0x000000000000000b 
0x000000c000365bf0:  0x000000c000365eb0  0x000000c000365d80 
0x000000c000365c00:  0x000000c000365c50  0x000000000047353d <runtime.sigtramp+0x000000000000003d> 
0x000000c000365c10: <0x000000000000000b  0x000000c000365eb0 
0x000000c000365c20:  0x000000c000365d80  0x000000c000365da8 
0x000000c000365c30:  0x000000c000365c98  0x0000000000000000 
0x000000c000365c40:  0x0000000000000000  0x0000000000000005 
0x000000c000365c50:  0x00007fdb954040a0 !0x00007fdb94f8cd77 
0x000000c000365c60: >0x0022000000000000  0x0000000000000001 
0x000000c000365c70:  0x000000c000365d80  0x00007fdb95404000 
0x000000c000365c80:  0x000000c000365eb0  0x0000000b0000000b 
0x000000c000365c90:  0x0000000000000000  0x0000000000000000 
0x000000c000365ca0:  0x0000000000000000  0x0000000000000032 
0x000000c000365cb0:  0x0000000000000019  0x000000c000365ce0 
0x000000c000365cc0:  0x0000000000517556 <reflect.Value.Kind+0x0000000000000036>  0x0000000000000199 
0x000000c000365cd0:  0x0000000000000019  0x0000000000000019 
0x000000c000365ce0:  0x000000c0003661e0  0x0000000000624a16 <encoding/json.(*decodeState).object+0x0000000000001416> 
0x000000c000365cf0:  0x00000000011dddc0  0x000000c00038c190 
0x000000c000365d00:  0x0000000000000199  0x0000000000000198 
0x000000c000365d10:  0x0000000000000000  0x0000000000000000 
0x000000c000365d20:  0x0000000000000000  0x000000000000002c 
0x000000c000365d30:  0x0000000000203000  0x0685c1413d43fb00 
0x000000c000365d40:  0x000000c0011825b8  0x000000c0007f4660 
0x000000c000365d50:  0x000000c000366e68  0x000000c0004c84e0 
runtime.throw({0x1288d91?, 0xc000072000?})
        /home/aidan/go/go1.18.6/src/runtime/panic.go:992 +0x71
runtime.sigNotOnStack(0xb)
        /home/aidan/go/go1.18.6/src/runtime/signal_unix.go:1002 +0x65
runtime.adjustSignalStack(0xb, 0xc000600000, 0x6?)
        /home/aidan/go/go1.18.6/src/runtime/signal_unix.go:577 +0x156
runtime.sigtrampgo(0xb, 0xc000365eb0, 0xc000365d80)
        /home/aidan/go/go1.18.6/src/runtime/signal_unix.go:467 +0x13b
runtime.sigtrampgo(0xb, 0xc000365eb0, 0xc000365d80)
        <autogenerated>:1 +0x2e
runtime: unexpected return pc for runtime.sigtramp called from 0x7fdb94f8cd77
stack: frame={sp:0xc000365c10, fp:0xc000365c60} stack=[0xc00035db10,0xc000365f10)
0x000000c000365b10:  0x000000000000000b  0x000000c000365b48 
0x000000c000365b20:  0x000000c000365b70  0x000000c000365b98 
0x000000c000365b30:  0x0020300000000000  0x000000c000010578 
0x000000c000365b40:  0x0000000000000000  0x000000c000604000 
0x000000c000365b50:  0x0000000000000000  0x0000000000008000 
0x000000c000365b60:  0x000000c000365bd8  0x000000000045533b <runtime.sigtrampgo+0x000000000000013b> 
0x000000c000365b70:  0x000000c00000000b  0x000000c000600000 
0x000000c000365b80:  0x0000000000000006  0x0000000000000005 
0x000000c000365b90:  0x0000000000000001  0x0000000000000000 
0x000000c000365ba0:  0x0000000000000000  0x0000000000000000 
0x000000c000365bb0:  0x0000000000000000  0x0000000000000000 
0x000000c000365bc0:  0x000000c000679040  0x000000c000365eb0 
0x000000c000365bd0:  0x000000c000365d80  0x000000c000365c00 
0x000000c000365be0:  0x000000000047408e <runtime.sigtrampgo+0x000000000000002e>  0x000000000000000b 
0x000000c000365bf0:  0x000000c000365eb0  0x000000c000365d80 
0x000000c000365c00:  0x000000c000365c50  0x000000000047353d <runtime.sigtramp+0x000000000000003d> 
0x000000c000365c10: <0x000000000000000b  0x000000c000365eb0 
0x000000c000365c20:  0x000000c000365d80  0x000000c000365da8 
0x000000c000365c30:  0x000000c000365c98  0x0000000000000000 
0x000000c000365c40:  0x0000000000000000  0x0000000000000005 
0x000000c000365c50:  0x00007fdb954040a0 !0x00007fdb94f8cd77 
0x000000c000365c60: >0x0022000000000000  0x0000000000000001 
0x000000c000365c70:  0x000000c000365d80  0x00007fdb95404000 
0x000000c000365c80:  0x000000c000365eb0  0x0000000b0000000b 
0x000000c000365c90:  0x0000000000000000  0x0000000000000000 
0x000000c000365ca0:  0x0000000000000000  0x0000000000000032 
0x000000c000365cb0:  0x0000000000000019  0x000000c000365ce0 
0x000000c000365cc0:  0x0000000000517556 <reflect.Value.Kind+0x0000000000000036>  0x0000000000000199 
0x000000c000365cd0:  0x0000000000000019  0x0000000000000019 
0x000000c000365ce0:  0x000000c0003661e0  0x0000000000624a16 <encoding/json.(*decodeState).object+0x0000000000001416> 
0x000000c000365cf0:  0x00000000011dddc0  0x000000c00038c190 
0x000000c000365d00:  0x0000000000000199  0x0000000000000198 
0x000000c000365d10:  0x0000000000000000  0x0000000000000000 
0x000000c000365d20:  0x0000000000000000  0x000000000000002c 
0x000000c000365d30:  0x0000000000203000  0x0685c1413d43fb00 
0x000000c000365d40:  0x000000c0011825b8  0x000000c0007f4660 
0x000000c000365d50:  0x000000c000366e68  0x000000c0004c84e0 
runtime.sigtramp()
        /home/aidan/go/go1.18.6/src/runtime/sys_linux_amd64.s:361 +0x3d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/aidan/go/go1.18.6/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x4718e1

goroutine 1 [syscall, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_gtk_main()
        _cgo_gotypes.go:1053 +0x45
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).RunMainLoop(0xc000099800)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/desktop/linux/frontend.go:57 +0x1c
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc000112aa0)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/app/app_dev.go:30 +0x72
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc0007e5038)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/pkg/application/application.go:69 +0x165
github.com/wailsapp/wails/v2.Run(0xc000125440)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/wails.go:14 +0x33
main.main()
        /home/aidan/code/go/nube/rubix-ui/main.go:36 +0x519

goroutine 6 [select]:
github.com/desertbit/timer.timerRoutine()
        /home/aidan/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0x11b
created by github.com/desertbit/timer.init.0
        /home/aidan/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x25

goroutine 7 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0000fc6c0)
        /home/aidan/go/pkg/mod/github.com/tidwall/buntdb@v1.2.9/buntdb.go:547 +0x105
created by github.com/tidwall/buntdb.Open
        /home/aidan/go/pkg/mod/github.com/tidwall/buntdb@v1.2.9/buntdb.go:169 +0x526

goroutine 25 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0xc000099800)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/desktop/linux/frontend.go:123 +0x3c
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/desktop/linux/frontend.go:109 +0x935

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x1808f00?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc000150098, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc000150098, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Read(0xc000150080, {0xc0003c8000, 0xe61, 0xe61})
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:167 +0x44f
net.(*netFD).Read(0xc000150080, {0xc0003c8000, 0xe61, 0xe61})
        /home/aidan/go/go1.18.6/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc00038e008, {0xc0003c8000, 0xe61, 0xe61})
        /home/aidan/go/go1.18.6/src/net/net.go:183 +0xa9
crypto/tls.(*atLeastReader).Read(0xc00038a2a0, {0xc0003c8000, 0xe61, 0xe61})
        /home/aidan/go/go1.18.6/src/crypto/tls/conn.go:785 +0xc2
bytes.(*Buffer).ReadFrom(0xc000396278, {0x18049e0, 0xc00038a2a0})
        /home/aidan/go/go1.18.6/src/bytes/buffer.go:204 +0x142
crypto/tls.(*Conn).readFromUntil(0xc000396000, {0x1805de0, 0xc00038e008}, 0x5)
        /home/aidan/go/go1.18.6/src/crypto/tls/conn.go:807 +0x172
crypto/tls.(*Conn).readRecordOrCCS(0xc000396000, 0x0)
        /home/aidan/go/go1.18.6/src/crypto/tls/conn.go:614 +0x1d8
crypto/tls.(*Conn).readRecord(0xc000396000)
        /home/aidan/go/go1.18.6/src/crypto/tls/conn.go:582 +0x2b
crypto/tls.(*Conn).Read(0xc000396000, {0xc00015a000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/crypto/tls/conn.go:1285 +0x217
bufio.(*Reader).Read(0xc0007f4cc0, {0xc0007e0120, 0x9, 0x9})
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:236 +0x373
io.ReadAtLeast({0x1804880, 0xc0007f4cc0}, {0xc0007e0120, 0x9, 0x9}, 0x9)
        /home/aidan/go/go1.18.6/src/io/io.go:331 +0x15c
io.ReadFull({0x1804880, 0xc0007f4cc0}, {0xc0007e0120, 0x9, 0x9})
        /home/aidan/go/go1.18.6/src/io/io.go:350 +0xa5
net/http.http2readFrameHeader({0xc0007e0120, 0x9, 0x9}, {0x1804880, 0xc0007f4cc0})
        /home/aidan/go/go1.18.6/src/net/http/h2_bundle.go:1566 +0xc5
net/http.(*http2Framer).ReadFrame(0xc0007e00e0)
        /home/aidan/go/go1.18.6/src/net/http/h2_bundle.go:1830 +0x125
net/http.(*http2clientConnReadLoop).run(0xc000019f58)
        /home/aidan/go/go1.18.6/src/net/http/h2_bundle.go:8820 +0x1a8
net/http.(*http2ClientConn).readLoop(0xc000394180)
        /home/aidan/go/go1.18.6/src/net/http/h2_bundle.go:8716 +0xdc
created by net/http.(*http2Transport).newClientConn
        /home/aidan/go/go1.18.6/src/net/http/h2_bundle.go:7444 +0xce5

goroutine 38 [syscall]:
os/signal.signal_recv()
        /home/aidan/go/go1.18.6/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        /home/aidan/go/go1.18.6/src/os/signal/signal_unix.go:23 +0x1d
created by os/signal.Notify.func1.1
        /home/aidan/go/go1.18.6/src/os/signal/signal.go:151 +0x2e

goroutine 39 [chan receive]:
github.com/wailsapp/wails/v2/internal/signal.Start.func1()
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/signal/signal.go:31 +0x2b
created by github.com/wailsapp/wails/v2/internal/signal.Start
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/signal/signal.go:29 +0xe7

goroutine 46 [IO wait]:
internal/poll.runtime_pollWait(0xffffffffffffffff?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0001e4018, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc0001e4018, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Accept(0xc0001e4000)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:614 +0x4a9
net.(*netFD).accept(0xc0001e4000)
        /home/aidan/go/go1.18.6/src/net/fd_unix.go:172 +0x72
net.(*TCPListener).accept(0xc00010e0d8)
        /home/aidan/go/go1.18.6/src/net/tcpsock_posix.go:139 +0x55
net.(*TCPListener).AcceptTCP(0xc00010e0d8)
        /home/aidan/go/go1.18.6/src/net/tcpsock.go:275 +0x67
github.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0xc00010e0d8})
        /home/aidan/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:957 +0x48
net/http.(*Server).Serve(0xc0007e17a0, {0x180be10, 0xc000194018})
        /home/aidan/go/go1.18.6/src/net/http/server.go:3039 +0x4c8
github.com/labstack/echo/v4.(*Echo).Start(0xc000130000, {0xc00004016a, 0xf})
        /home/aidan/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:663 +0x167
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func4(0xc000130000, 0xc0007e5050)
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/devserver/devserver.go:114 +0x54
created by github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/devserver/devserver.go:113 +0xcd4

goroutine 1043 [select]:
net/http.(*persistConn).writeLoop(0xc0000fa360)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2392 +0x16e
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1751 +0x27e7

goroutine 1009 [IO wait]:
internal/poll.runtime_pollWait(0x1808f00?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0000e8518, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc0000e8518, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Read(0xc0000e8500, {0xc000488000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:167 +0x44f
net.(*netFD).Read(0xc0000e8500, {0xc000488000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc0007c6048, {0xc000488000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/net.go:183 +0xa9
net/http.(*persistConn).Read(0xc00028e120, {0xc000488000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1929 +0x1dc
bufio.(*Reader).fill(0xc000596480)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc000596480, 0x1)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:144 +0x178
net/http.(*persistConn).readLoop(0xc00028e120)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2093 +0x269
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1750 +0x277e

goroutine 1063 [IO wait]:
internal/poll.runtime_pollWait(0x1808f00?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0003e4598, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc0003e4598, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Read(0xc0003e4580, {0xc0000d2000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:167 +0x44f
net.(*netFD).Read(0xc0003e4580, {0xc0000d2000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc000010050, {0xc0000d2000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/net.go:183 +0xa9
net/http.(*persistConn).Read(0xc000269d40, {0xc0000d2000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1929 +0x1dc
bufio.(*Reader).fill(0xc0000981e0)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc0000981e0, 0x1)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:144 +0x178
net/http.(*persistConn).readLoop(0xc000269d40)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2093 +0x269
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1750 +0x277e

goroutine 1042 [IO wait]:
internal/poll.runtime_pollWait(0x1808f00?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc000536b18, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc000536b18, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Read(0xc000536b00, {0xc000729000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:167 +0x44f
net.(*netFD).Read(0xc000536b00, {0xc000729000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc0001940c0, {0xc000729000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/net.go:183 +0xa9
net/http.(*persistConn).Read(0xc0000fa360, {0xc000729000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1929 +0x1dc
bufio.(*Reader).fill(0xc000521ec0)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc000521ec0, 0x1)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:144 +0x178
net/http.(*persistConn).readLoop(0xc0000fa360)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2093 +0x269
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1750 +0x277e

goroutine 1138 [select]:
net/http.(*persistConn).writeLoop(0xc00028e120)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2392 +0x16e
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1751 +0x27e7

goroutine 1064 [select]:
net/http.(*persistConn).writeLoop(0xc000269d40)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2392 +0x16e
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1751 +0x27e7

goroutine 1106 [select]:
net/http.(*persistConn).writeLoop(0xc0000fa6c0)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2392 +0x16e
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1751 +0x27e7

goroutine 929 [IO wait]:
internal/poll.runtime_pollWait(0x1808f00?, 0x72)
        /home/aidan/go/go1.18.6/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0003e4298, 0x72, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.(*pollDesc).waitRead(0xc0003e4298, 0x0)
        /home/aidan/go/go1.18.6/src/internal/poll/fd_poll_runtime.go:88 +0x37
internal/poll.(*FD).Read(0xc0003e4280, {0xc00074f000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/internal/poll/fd_unix.go:167 +0x44f
net.(*netFD).Read(0xc0003e4280, {0xc00074f000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc00053e0b8, {0xc00074f000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/net.go:183 +0xa9
net/http.(*persistConn).Read(0xc0000fa6c0, {0xc00074f000, 0x1000, 0x1000})
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1929 +0x1dc
bufio.(*Reader).fill(0xc0007f4b40)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc0007f4b40, 0x1)
        /home/aidan/go/go1.18.6/src/bufio/bufio.go:144 +0x178
net/http.(*persistConn).readLoop(0xc0000fa6c0)
        /home/aidan/go/go1.18.6/src/net/http/transport.go:2093 +0x269
created by net/http.(*Transport).dialConn
        /home/aidan/go/go1.18.6/src/net/http/transport.go:1750 +0x277e

goroutine 1155 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).processMessage
        /home/aidan/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/desktop/linux/frontend.go:350 +0x874

````

**Comment by RaiBnod** [comment]
Fixes have been done recently on wails:

- https://github.com/wailsapp/wails/pull/2152
- https://github.com/wailsapp/wails/issues/2134
